### PR TITLE
Update example to match current standard

### PR DESCRIPTION
**Pull request by tarebyte**
I was trying to use the example, and it didn't seem like it fit what the new packages looked like.

Thanks!

### CODE REVIEW

**Comment by technicalpickles** [comment]
Did you just run the `yo hubot:script` generator and copy the files in? This repository predates the generator quite a bit.

**Comment by tarebyte** [comment]
Nope, I completely missed the fact that there was a yeoman generator! I had looked at a recently updated project and modified the files to look accordingly. Sorry about that.

Instead of updating the code, would it be more advantageous to just put something on the README that says to use `yo hubot:script`.

**Comment by technicalpickles** [comment]
@tarebyte I just did that in https://github.com/hubot-scripts/hubot-example/pull/10 . Thanks for putting this together, and good luck in your hubot scripting adventures!

**Comment by tarebyte** [comment]
Thanks @technicalpickles!

**Pull request closed without merging**
